### PR TITLE
Copy Audiobookly

### PR DESCRIPTION
**Pull request by Hackmodford**
I have taken Audiobookly and made some modifications.
* Renamed to `Audiobookshelf`
* Renamed the api sub project to `audiobookshelf_api`
* Removed references to Plex/Emby/etc.

I'm only requesting this be merged into main because it's the only branch and I do not have permission to create new ones.

### CODE REVIEW

**Comment by k9withabone** [comment]
Whoops sorry about that, you should have write permissions now so you can create a new branch. Also I'm not sure we can legally use Audiobookly until @keaganhilliard adds a license? See the [open source guide](https://opensource.guide/legal/#why-do-people-care-so-much-about-the-legal-side-of-open-source).

**Comment by Hackmodford** [comment]
Of course. We are humbly requesting the blessing of @keaganhilliard

**Comment by keaganhilliard** [comment]
You are good to go. I added an MIT license on my repo and pushed up a couple of things I had been working on.

**Comment by Hackmodford** [comment]
@keaganhilliard Do you have a summary of what changed? Is it worth trying to incorporate into this PR?

**Comment by keaganhilliard** [comment]
@Hackmodford Main thing was that I added getSeries and getBooksFromSeries methods, and I changed the model AbsAudiobook model to coerce the series attribute to a list if it doesn't come back as a list. Other than that there were some MacOS ui changes so I'm not really sure if you care about those parts.

**Pull request merged**
